### ISSUE TITLE
Windows Defender identifies this as a virus

### ISSUE THREAD

**Issue by LockeColeFF** [darkxex/UnCapFF6PRemaster#1]
Can't download it with edge and can't run it.  It's flagged as a virus.

**Comment by darkxex** [comment]
use google chrome

**Comment by LockeColeFF** [comment]
Same behavior in Chrome.  It will download but Windows defender still flags it a s a virus and will not run it.

**Comment by darkxex** [comment]
And what is the problem, just disable the defender or just not Download this.
